---

#- name: Add AWS EBS CSI helm repo
#  kubernetes.core.helm_repository:
#    name: aws-ebs-csi-driver
#    repo_url: "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"

#- name: Update the repository cache
#  kubernetes.core.helm:
#    name: foo
#    namespace: kube-system
#    state: absent
#    update_repo_cache: true

- name: Get AWS access key from CLI credentials file
  ansible.builtin.set_fact:
      aws_access_key_id: "{{ lookup( 'ini', 'aws_access_key_id section=snowballEdge file={{ ansible_env.HOME }}/.aws/credentials' ) }}"
      aws_secret_access_key: "{{ lookup( 'ini', 'aws_secret_access_key section=snowballEdge file={{ ansible_env.HOME }}/.aws/credentials' ) }}"

  #TODO: Change this to an ansible k8s task
- name: Create AWS Credentials Secret
  ansible.builtin.command: oc create secret generic aws-secret --namespace kube-system --from-literal "key_id={{ aws_access_key_id }}" --from-literal "access_key={{ aws_secret_access_key }}"
  ignore_errors: true
#  kubernetes.core.k8s:
#    state: present
#    namespace: kube-system
#    wait: true
#    definition:
#      apiVersion: v1
#      data:
#        access_key: "{{ aws_access_key_id | b64encode }}"
#        key_id: "{{ aws_secret_access_key | b64encode }}"
#      kind: Secret
#      metadata:
#        name: aws-secret
#        namespace: kube-system
#      type: Opaque
#    template: "{{ playbook_dir }}/roles/aws_ebs_csi/templates/aws-secret.yaml.j2"

  #TODO: Change this to an ansible k8s task
- name: Create secret with the SBE EC2 endpoint and port
  ansible.builtin.command: oc create secret generic aws-meta --namespace kube-system --from-literal "endpoint=https://{{ non_s3_endpoint }}:{{ ec2_port }}"
  ignore_errors: true
#  kubernetes.core.k8s:
#    state: present
#    namespace: kube-system
#    wait: true
#    template: 'aws-meta.yaml.j2'

- name: Slurp Snowball CA
  ansible.builtin.slurp:
    src: '/etc/pki/ca-trust/source/anchors/snow_cert.pem'
  register: slurped_sbe_api_ca_bundle_64

- name: Remove AWS CA temp file
  ansible.builtin.file:
    path: "/tmp/aws-ca-bundle-configmap-prep.yaml"
    state: absent

- name: Create AWS CA Config Map template locally
  template:
    src: aws-ca-bundle-configmap.j2
    dest: "/tmp/aws-ca-bundle-configmap-prep.yaml"
    mode: 0664

- name: Ensure proper spacing of AWS CA Bundle Config Map yaml
  shell: awk 'BEGIN{c=0}  /BEGIN CERTIFICATE/{c=1}  {if (c==1) print "   ",$0}  {if (c==0) print $0}  /END CERTIFICATE/{c=0}' '/tmp/aws-ca-bundle-configmap-prep.yaml'
  register: aws_ca_bundle_spaced

- name: Remove AWS CA temp file
  ansible.builtin.file:
    path: "/tmp/aws-ca-bundle-configmap-prep.yaml"
    state: absent

- name: Create AWS API CA Bundle ConfigMap
  kubernetes.core.k8s:
    state: present
    namespace: kube-system
    wait: true
    definition: '{{ aws_ca_bundle_spaced.stdout | from_yaml }}'

#- name: Ensure helm values temp location is free
#  ansible.builtin.file:
#    path: "/tmp/values.yaml"
#    state: absent

- name: Create helm chart values file from template
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/roles/aws_ebs_csi/templates/values.yaml"
    regexp: 'snowball_ec2_endpoint'
    replace: "https://{{ non_s3_endpoint }}:{{ ec2_port }}"

- name: Install AWS EBS CSI Driver
  kubernetes.core.helm:
    name: aws-ebs-csi-driver
    namespace: kube-system
    chart_ref: aws-ebs-csi-driver/aws-ebs-csi-driver
    values_files:
      - "{{ playbook_dir }}/roles/aws_ebs_csi/templates/values.yaml"
