---

- name: Stage ignition files (httpd)
  become: true
  delegate_to: localhost
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/www/html/ignition/"
    owner: root
    group: root
    mode: 0444
  loop:
    - "/opt/openshift/cluster/bootstrap.ign"
    - "/opt/openshift/cluster/master.ign"
    - "/opt/openshift/cluster/worker.ign"
