---
- hosts: localhost
  gather_facts: true
  become: false
  tasks:

    - name: Get snowball endpoint and port information
      include_role:
        name: get_snowball_service_ports

    - name: Deploy AWS EBS CSI Storage Driver
      include_role:
        name: aws_ebs_csi
