---
- hosts: localhost
  gather_facts: true
  become: true
  tasks:

      # Must use import_role due to tag usage
    - name: Install and Configure HAProxy for Load Balancing
      import_role:
        name: haproxy
