---

#- name: Install pip
#  ansible.builtin.package:
#    name: 'python3-pip'
#    state: present

#- name: install requirements
#  ansible.builtin.pip:
#    name: "{{ httpd_requirements }}"
#    state: present
#    executable: "{{ pip_cmd }}"

- name: install apache httpd
  ansible.builtin.package:
    name: "{{ httpd_packages }}"
    state: present

- name: modify selinux settings
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop: "{{ httpd_sebooleans }}"

- name: allow connections to custom port
  community.general.seport:
    ports: '{{ item }}'
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop:
    - "{{ httpd_port }}"
    - "{{ httpd_ssl_port }}"

- name: Populate service facts
  service_facts:

- name: Allow http server ports in firewall
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    port: '{{ item }}/tcp'
  with_items:
    - "{{ httpd_port }}"
    - "{{ httpd_ssl_port }}"
  when:
    ('firewalld.service' in services) and
    (ansible_facts.services["firewalld.service"].state is match("running"))

- name: create ssl directory
  ansible.builtin.file:
    path: "{{ httpd_config_directory }}/ssl"
    state: directory

- name: create ssl key
  community.crypto.openssl_privatekey:
    path: "{{ httpd_config_directory }}/ssl/{{ httpd_ssl_servername }}.key"
  register: httpd_key

- name: create ssl csr
  community.crypto.openssl_csr:
    path: "{{ httpd_config_directory }}/ssl/{{ httpd_ssl_servername }}.csr"
    privatekey_path: "{{ httpd_key.filename }}"
    common_name: "{{ httpd_ssl_servername }}"
  register: httpd_csr

- name: create ssl certificates
  community.crypto.x509_certificate:
    path: "{{ httpd_config_directory }}/ssl/{{ httpd_ssl_servername }}.crt"
    privatekey_path: "{{ httpd_csr.privatekey }}"
    csr_path: "{{ httpd_csr.filename }}"
    provider: selfsigned

- name: configure ssl
  ansible.builtin.template:
    src: ssl.conf.j2
    dest: "{{ httpd_config_directory }}/ssl.conf"
  notify:
    - test httpd configuration validity
    - restart httpd

- name: configure locations
  ansible.builtin.template:
    src: location.conf.j2
    dest: "{{ httpd_config_directory }}/{{ item.name }}.conf"
  loop: "{{ httpd_locations }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - httpd_locations is defined
  loop_control:
    label: "{{ item.name }}"

- name: configure vhosts
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: "{{ httpd_config_directory }}/{{ item.name }}.conf"
  loop: "{{ httpd_vhosts }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - httpd_vhosts is defined
  loop_control:
    label: "{{ item.name }}"

- name: configure httpd
  ansible.builtin.template:
    src: "{{ httpd_config_src }}"
    dest: "{{ httpd_config_dest }}"
  notify:
    - test httpd configuration validity
    - restart httpd

- name: configure redirect from http to https
  ansible.builtin.template:
    src: default_vhost.conf.j2
    dest: "{{ httpd_config_directory }}/default_vhost.conf"
  when: ( httpd_redirect_to_ssl | bool )
  notify:
    - test httpd configuration validity
    - restart httpd

- name: create docroot
  ansible.builtin.file:
    path: "{{ item.documentroot }}"
    state: directory
  loop: "{{ httpd_vhosts }}"
  when:
    - httpd_vhosts is defined
    - item.documentroot is defined

- name: Create ignition serving directory
  ansible.builtin.file:
    path: "/var/www/html/ignition"
    state: directory

- name: configure bootstrap ignition loader
  ansible.builtin.template:
    src: merge_bootstrap.ign.j2
    dest: "/var/www/html/ignition/merge_bootstrap.ign"

- name: configure master ignition loader
  ansible.builtin.template:
    src: merge_master.ign.j2
    dest: "/var/www/html/ignition/merge_master.ign"

- name: start and enable httpd
  ansible.builtin.service:
    name: "{{ httpd_service }}"
    state: started
    enabled: true
